- database/sqls/init_tables.sql
- frontend/.gitignore
DBのテーブル定義と初期にテーブルにINSERTされるデータを記載した．
初期にデータが入るテーブルは以下の通り
- status
- place
- grade
- avatar
- user
- #3 
- #4
> DBのスキーマと初期データを定義する

- frontend/src/api.ts
- frontend/src/routes/Home/index.tsx
- frontend/src/routes/Profile/index.tsx
- frontend/src/schema/api.ts
- openapi.yaml
- Api-schemaを修正したことにより，api名が変わったため，frontendでimportしてる箇所でエラーが発生している．
- スキーマを正しい名前でimportする
- #54
> 【Frontend】Api-schemaを更新したことによるバグの修正

- .github/ISSUE_TEMPLATE/custom.md
> Issueテンプレートのタイトルにある機能名をタグに移行

- frontend/src/routes/Home/index.tsx
- Avaterの表示をProfileと統一したい
- そもそも正しく表示されているか微妙
- Avaterの表示が正しいか確認
- デザインをProfile画面と統一する
- #58
> Avaterの表示が正しいか確認＆デザインを変更する

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/api.ts
- frontend/src/features/MobileNav/index.tsx
- frontend/src/features/NavItem/index.tsx
- frontend/src/features/SidebarContent/index.tsx
- frontend/src/routes/AccessHistory/access_history.css
- frontend/src/routes/AccessHistory/index.tsx
- frontend/src/routes/Profile/index.tsx
- frontend/yarn.lock
- Access historyページを作成する
- トグルボタンで月を変更できるようにしたい
- #47
> 【Access history】Access historyページを作成する

- backend/internal/repositories/lab_asistant_member_repository.go
- api-schemaを変更したのでそれに伴ってresoponseを変更
- LAのメンバーを取得するAPIの改修
- api-schemaに合わせる
- #93
> LAのメンバーを取得するAPIの改修

- backend/internal/controllers/avatar_controller.go
- backend/internal/controllers/lab_assistant_schedule_controller.go
- backend/internal/controllers/users_controller.go
- backend/internal/repositories/avatar_repository.go
- backend/internal/repositories/users_repository.go
- backend/internal/routers.go
- backend/internal/schema/model_get_user_by_id_200_response_avatar_list_inner.go
- backend/internal/services/avatar_service.go
- database/sqls/init_tables.sql
- frontend/src/features/AvatarList/index.tsx
- frontend/src/features/Banner/index.tsx
- frontend/src/routes/Profile/index.tsx
- frontend/src/schema/api.ts
- openapi.yaml
- DB定義が変更したため，それに伴ってデザインを変更する
- DB定義とスキーマの修正
- avatarをdeleteするapiの実装
- profile画面の修正
- #100 
- #101 
- #105 
deleteボタンを設置してavatarを消せるようにしました．
defaultのavatarは削除できないようにした．
また，avatarをクリックするとavatar変更する仕様から変更Iconをクリックするとavatarを変更できるようにした．
> Profile画面の改修

- frontend/src/routes/LabAssistant/index.tsx
- シフトメンバーがスクロールできなくなっていたので修正
- overflowを修正
- #85
> LAシフトボードを入力する画面を作成する（修正）

- frontend/src/features/RankingList/index.tsx
- #97 
- 既存のランキングの配列に`rank`を追加し、同じ成績のユーザには同じ順位が割り当てられ、順位の飛びも適切に処理する
- 同じ日数の場合、意図した表示ができることを確認しました
> ランキング項目の結果が同率だった場合、順位表示は同じにする

- backend/internal/controllers/access_history_controller.go
- backend/internal/repositories/access_history_repository.go
- backend/internal/routers.go
- backend/internal/services/access_history_service.go
- frontend/src/schema/.openapi-generator/FILES
- frontend/src/schema/api.ts
- openapi.yaml
- #111 
- pathparameterをdateからmonthに変更する
- 影響範囲のある箇所を変更する
- 動作に影響がないことを確認済
> 入退室履歴のAPIでpathparameterをdateからmonthに変更する

- backend/internal/schema/model_post_user_information_request.go
- backend/internal/schema/model_put_change_password_request.go
- frontend/src/schema/api.ts
- openapi.yaml
- #165 
- auth_user_nameとgrade_nameがないため追加する
- grade_nameの一覧表示のためのapiを定義
-
> Sign upのスキーマ定義を修正する

- frontend/src/features/Banner/index.tsx
- #177 
- nullの場合はRoleを表示しないようにする
- RoleがないユーザはRoleを表示しない
> Roleがないユーザのprofile画面の修正

- backend/internal/controllers/grade_controller.go
- backend/internal/controllers/role_controller.go
- backend/internal/repositories/grade_repository.go
- backend/internal/repositories/role_repository.go
- backend/internal/routers.go
- backend/internal/services/grade_service.go
- backend/internal/services/role_service.go
- frontend/src/schema/api.ts
- openapi.yaml
- #181 
- #182
- RoleテーブルからRole一覧を取得し返すAPIを実装する
- Gradeテーブルからgrade_nameを全て取得する
- role一覧を取得
- grade一覧を取得
> Role一覧とgrade一覧を取得するAPIを実装する

- frontend/src/features/SettingInfo/index.tsx
- #190 
- 題名の通り
- 一通り画面が動くことを確認しました
> 【緊急】targetUserInfo やrole_listが読み込まれる前でもエラーを回避する

- backend/internal/models/grade_model.go
- backend/internal/repositories/grade_repository.go
- backend/internal/services/task_scheduler.go
- #192 
- 4月1日に全ユーザの学年を上げる
- OBは更新しない
- U4は自動的にM1に進級する
- M2は進級せずOBに更新する
- 学年を更新するSQLクエリが正しく動作していることを確認
U4で卒業する学生がいるため，チーフは卒業した学生はM1からOBに手動で変更する作業が発生
> 学年を自動更新するjobを実装する

- backend/internal/services/lab_assistant_schedule_service.go
- backend/internal/services/task_scheduler.go
- frontend/src/routes/LabAssistant/index.tsx
- #200 
- #172
- タイトルの部分の文字が潰れている
- LA担当の最終日が存在しない場合（担当回数が0の場合）「担当経験なし」と表示するようにする
- PDFにした場合
- 最終LA日程がない場合
> LAのPDFを改善する

- frontend/src/features/Banner/index.tsx
- #180 
- SettingでRoleバッジを作成してくれたのでProfileでも適用する
- roleをバッジに変更
> ProfileのRoleをバッジにする

- frontend/src/features/MobileNav/index.tsx
- #189 
- ranking画面のzindexを調整
- 正しくUIが表示されることを確認しました
> ranking画面においてUIの前面配置を調整する

- frontend/nginx.conf
-
- server_nameをlocalhostからデプロイ先のipに変更しました
-
> nginxのserver_nameを修正

- backend/internal/schema/model_put_change_password_request.go
- frontend/src/schema/api.ts
- openapi.yaml
- #224 
- pathparaでuser_idを追加する
- auth_user_nameを削除する
-
> Password変更のスキーマを修正する

- Makefile
-
- docker-composeコマンドはv1系のコマンドなので古い．docker composeにしてv2系にした．
- Ubuntuのdocker-composeをv2系にupgradeした
-
> makefileを修正

- Makefile
> makefileの修正

- frontend/Dockerfile
> dockerfileのdev環境とprod環境の入れ替え

- frontend/Dockerfile
> yarn installを修正

- .env.prod
> backend_endpointをlocalhostに

- .env.prod
> localhost to serverIp

- backend/internal/repositories/sign_up_repository.go
- database/sqls_dev/init_tables_dev.sql
- database/sqls_prod/init_tables_prod.sql
- #242 
- user_possession_avatarテーブルに初期アイコン画像を追加する
- 動作検証済み
> SignUpする際にuser_possession_avatarテーブルに初期アイコンを追加する

- .env.dev
- .env.prod
- backend/internal/controllers/status_controller.go
- frontend/src/routes/Home/index.tsx
- #155 
- Backendにアクセスするユーザのネットワークを取得する
- ユーザが研究室内のネットワークに存在しない場合は入室ボタンを押すとエラーになるようにする
- 本番環境で動作検証済
> 研究室のWiFi環境のみ入室ボタンを押すことを可能する

- .github/workflows/deploy.yml
-
- リリースの時のみGHAが動作するようにしました．
-
> GHAのmainにmergeしたときの処理を削除

- docker-compose.yml
- nginx/nginx.conf
> プロキシのポートをHTTPS（80から443）に変更

- .github/workflows/deploy.yml
> GHAリモートサーバからレンタルサーバにSSL証明書を転送_ver2

- .github/workflows/deploy.yml
-
- source: "~/ISDL-Sentinel/proxy/ssl/*"の部分でエラーが吐かれている可能性があるため修正
-
> GHAリモートサーバからレンタルサーバにSSL証明書を転送_ver3

- backend/internal/services/status_service.go
-
- PlaceIdが退出時に0に設定されているため，入退室履歴に不具合が生じていた．なのでKC104のIDを代入するように修正
-
> PlaceIdが0になっていたため修正

- .github/workflows/deploy.yml
- backend/internal/controllers/status_controller.go
- backend/internal/infrastructures/credentials/.gitignore
- backend/internal/repositories/status_repository.go
> statusが更新されないバグを解消

- frontend/src/features/MobileNav/index.tsx
> biometricsの表示を変更

- README.md
- backend/internal/repositories/ranking_repository.go
- #266 
- leaving_historyのstay_timeを用いるようにする。
- dev環境で出席中に滞在時間が正しく表示されることを確認しました。
- 退室した後に滞在時間が加算されます
> ランキングの滞在時間を算出する方法を修正

- backend/internal/repositories/status_repository.go
- backend/internal/services/task_scheduler.go
- #270
- #271
- 強制退室させた人に対してis_last_leavingをtrueとするように変更
- 強制退室者が複数存在する場合は1名だけtrueとする
- 強制退室者が1名の場合と複数名の場合で動作検証済み
> 入室したユーザが強制退室したユーザのみの場合退室履歴に表示されない

- backend/internal/repositories/status_repository.go
- backend/internal/services/task_scheduler.go
- #274 
- 宿泊者がいる場合はis_last_leavingをfalseにする．
- dev環境で動作検証済
> 強制退出処理で宿泊者がいる場合のバグ修正
