.gitignore, backend/.openapi-generator/FILES, backend/internal/controllers/avatar_controller.go, backend/internal/controllers/users_controller.go, backend/internal/repositories/avatar_repository.go, backend/internal/routers.go, backend/internal/schema/model_avatar.go, backend/internal/services/avatar_service.go, backend/tmp/air.log, frontend/src/schema/api.ts, openapi.yaml
- Avatarを変更するAPIを実装する
- `PUT /avatar`をスキーマを基に作成する
- 変更内容はDBに反映させること
このAPIはuserテーブルのavatar.idを更新するのみであるため，responseはsuccessの文字列を返している．
更新されたavatar.idをresponseとして返すことも可能．
- #22
=> 【Profile】Avatarを変更するAPIを実装する

backend/internal/infrastructures/db.go, backend/internal/models/status_model.go, backend/internal/repositories/status_repository.go, backend/internal/services/status_service.go
- 現状、入退室をした際ステータスを変えるだけでは、退室しているのに場所は'KC104'などになってしまうのでその対応を前のIssueから分割した
- 入退室処理と同時に場所の情報も更新する
- 入室した際にentering_historyに現在時刻を追加
- 退室した際はそのuser_idに該当するentering_historyのレコードから一番直近の時刻を取得し差分を算出
- 算出した差分を滞在時間として現在時刻とともにentering_historyに追加
- #37 
- #38 
（DBのトランザクションとか分けるとやりづらかったので、2つ一気にPR作りました）
- 入室ボタンを押した時に入室者一覧に表示され、場所がKC104になっている
- 退室ボタンを押した際に履歴テーブルに退室時間と滞在時間が記録されている
=> 入退室を行った際にplace_idを変更し、historyにも保存する

frontend/src/routes/Home/index.tsx
- 表示時間が7分ずれているので修正したい
- dayjsでdecodeするときにminutes（mm）で指定するところを、month（MM）で指定していたので修正
- #56
=> 入室時刻の表示ズレを修正する

frontend/src/routes/Home/index.tsx
- 現状出席者がいない場合、表のヘッダーのみ表示されるのでデザイン的にイマイチ
- 出席者一覧が空配列の場合、文言を変更する
- #71
=> 出席者がいない場合、「出席者はいません」と表示する

frontend/src/features/RankIcon/Top3Icon.tsx, frontend/src/features/RankingList/index.tsx, frontend/src/routes/Ranking/index.tsx
- 出席日数をAPIから取得することはできたが、画面がまだだったので実装
- 出席日数を各ユーザ取得し、その総和を降順で表示する
- APIでの処理が完了しておらずランキングリストが空の場合はレンダリングしないようにする
- ランキングのアバターにアクセス履歴と同じclickイベントを追加する
- #50 
- #102 
- #103
=> 出席日数のランキング表示およびバグ修正

backend/internal/repositories/lab_assistant_member_repository.go, backend/internal/schema/model_get_lab_assistant_member_200_response_inner.go, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/api.ts, frontend/src/features/SidebarContent/index.tsx, frontend/src/routes/LabAssistant/index.tsx, frontend/src/schema/api.ts, frontend/yarn.lock, openapi.yaml
- LAシフトボードを入力する画面を作成する
- memberを取得するAPIに最後に行ったLA日程（last_shift_day）を追加する
- apiスキーマの更新（last_shift_day）
- lab_assistant_member_repository.goの修正
- LAシフト表のページ作成
- LAシフト表のPDF化
- 初回レンダリング時は今月のLAを表示
- カレンダーは月に合わせて正しい日にちと曜日になる
- 選択形式でメンバーを選択し，「登録ボタン」をクリックするとDBに登録完了
- 変更したい場合も同様に「登録ボタン」をクリックすると変更を反映
- 「PDF化ボタン」をクリックするとシフト表をPDF化可能
- LAメンバーには名前，最終LA日程，LA回数を表示
- #85 
- #109
=> LAシフトボードを入力する画面を作成する

backend/internal/infrastructures/calendar.go, backend/internal/models/calendar.go, database/sqls/init_tables.sql
- GoogleCalendarアプリ上からKC101【小教室】のカレンダーIDを確認できなかったため、calendarAPIで予定を取得する時にKC101【小教室】の分だけ取得できていない
- 一斉取得の処理にKC101【小教室】のカレンダーIDを追加する
- userテーブルにentered_atを設ける（今後のタスクのため。差分少ないので一緒にやってます）
- #115 
- #117
=> calendarAPIの全件取得にKC101【小教室】のカレンダーIDを追加する

frontend/src/features/Loading/Loading.tsx, frontend/src/routes/Home/index.tsx
- 出席者一覧を取得する際に、取得前は「出席者はいません」と表示される仕様だが、calendarAPIの追加によって応答時間が長くなってしまったので、目立つしなんとかしたい
- APIから応答待ちの時は出席者一覧にその文言を表示する
- #116
=> calendarAPIの処理待ちにLoading画面を正しく表示する

backend/internal/repositories/attendees_list_repository.go, frontend/yarn.lock
- #141 
- #142 
- calendar経由で出席する処理でstatusを`In Room`にしている部分を削除（KC104の出席状況に委ねる）
- 以下の予定を登録し、予定中でも出席者一覧に表示するかどうかは、出席状況に依存することを確認しました
calendarから取得した部屋が出力される
=> calendarAPIの予定経由でstatusを出席にしないようにする

frontend/src/App.tsx, frontend/src/features/RoleBadge/index.tsx, frontend/src/features/SettingInfo/index.tsx, frontend/src/features/SidebarContent/index.tsx, frontend/src/features/UserList/index.tsx, frontend/src/routes/Home/index.tsx, frontend/src/routes/UserSetting/index.tsx
- #157 
- Setting画面のデザインを実装
- ユーザ一覧にあるユーザを選択すると右側にその情報を表示
- **今回実装をしないであろう機能はサイドバーから削除**
---
下記の理由から一覧にOBを含めるかどうかの処理、実際の編集モードは未実装
- コードが長いしレビューがしんどい（見落とす）
- デザインを固めてから実装に移りたい
- https://github.com/ISDL-dev/ISDL-Sentinel/pull/171 において役割一覧をAPIから取得するかを検討中なので、その部分の実装も保留して現在の進捗を共有するため
- 概ねFigmaのデザインで作成できていることを確認しました
- 一覧で選択した際該当ユーザの情報が表示できることを確認しました
=> Setting画面のデザインを実装する

frontend/src/routes/Home/index.tsx
- #176 
- スクロールなしにtableを見れるようにする
=> ホーム画面のテーブルをスクロールなしに表示する

frontend/src/features/SettingInfo/index.tsx, frontend/src/models/role/role.ts, frontend/src/routes/LabAssistant/index.tsx, frontend/src/userContext.tsx
- #159 
- LAの画面はRoleにinfraがないユーザの場合、メンバーを変更できないようにする
- Setting画面はRoleにchefがないユーザの場合、メンバーの権限を変更できないようにする
- LAとsettingの権限を適用できていることを確認しました
=> 各画面をユーザのroleに基づく表示にする

backend/internal/repositories/attendees_list_repository.go, backend/internal/repositories/ranking_repository.go
- #169 
- 出席者に表示させないようにする（念の為）
- ランキングのための情報をAPIから取得の際にOBは含めない
- gradeがOBのdummyユーザを作成
- dummyが出席しても出席者一覧に表示されないことを確認しました
- ランキングに表示できる順位でもOBの場合は表示されないことを確認しました
=> gradeが「OB」のユーザはSetting以外の機能で無効化する

frontend/src/features/RoleBadge/index.tsx, frontend/src/features/SettingInfo/index.tsx, frontend/src/features/UserList/index.tsx, frontend/src/models/grade/grade.ts, frontend/src/models/role/role.ts, frontend/src/routes/UserSetting/index.tsx
- #196 
- #197 
- ユーザ情報を更新した際Toastで通知をする
- 在学生を上部に表示し、学年順に整列させる
- モバイル用に一部対応できていない箇所があるので修正
- 登録処理が完了したときにToastが表示できることを確認しました
- ユーザ一覧でOBが在校生よりも下部に表示されることを確認しました
- モバイルデザイン
=> Setting画面のUI/UX改善を行う

frontend/src/App.tsx, frontend/src/features/MobileNav/index.tsx, frontend/src/routes/RegisterWebauthn/index.tsx
- #201 
- プルダウンに生体認証登録を追加する
- SignInページからregisterボタンを削除する
- login後にプルダウンで生体認証登録ボタン
- Register
- Sign In
=> WebAuthnのRegisterボタンを削除してプルダウンに移動する

backend/internal/controllers/change_password_controller.go, backend/internal/repositories/change_password_repository.go, backend/internal/routers.go, backend/internal/services/change_password_service.go
- chage passwordスキーマの変更（auth_user_nameの削除）に応じてauth_user_nameの代わりにパスパラメータのidを利用
- パスワードの変更、ログイン成功
- 変更前パスワードでログイン失敗
=> chage passwordスキーマの変更に応じてchange password apiを修正

.env.dev, .env.prod, backend/internal/controllers/digest_auth_login_controller.go, backend/internal/routers.go, backend/internal/services/webauthn_registration_service.go, docker-compose.yml, frontend/src/routes/SignInDigest/index.tsx, nginx/nginx.conf
- #240 
- リバースプロキシを追加してアクセスを80portだけにする．
- コンテナ内はコンテナ間通信をするようにする．（サーバのipを叩かずにコンテナ名で通信する）
- [http://160.251.121.161/](http://160.251.121.161/)でアクセス可能なことを確認
- frontendとbackendが通信可能なことを確認
- WebAuthnのAPIがhttps通信 or localhostのみ使用可能なため，prod環境では使用できない．したがって，https化する必要性がある
- Digest認証でログインしようとするとポップアップでloginが求められる．これはheaderで`www-authenticate`を追加しているためである．そのため，この名前を変更する必要性がある．
=> リバースプロキシを追加する

.github/workflows/deploy.yml
-
- 発行済みSSL証明書（.pem）と秘密鍵（.key）をgithub secretsにbase64でエンコードしたものを保存しproxy/ssl直下にデコードするように追加
-
=> SSL証明書をデコード

.github/workflows/deploy.yml
-
- base64でデコードしたファイルはGHAのリモートサーバに保存
- その後scpでレンタルサーバに転送処理を追加
-
=> GHAリモートサーバからレンタルサーバにSSL証明書を転送

frontend/src/features/RankingList/index.tsx
- #268 
- ランキングのアイコンにChakraのAvaterを使用
- アイコンが正しく表示できることを確認しました
**モバイル表示**
=> ランキングのユーザアイコンにAvaterを使用し他の画面と統一する
